name: Android CI
on: [push, pull_request]

env:
  ANDROID_DIR: VerumOmnisApp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Build Debug APK
        working-directory: ${{ env.ANDROID_DIR }}
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ${{ env.ANDROID_DIR }}/app/build/outputs/apk/debug/*.apk
